### ISSUE TITLE
ERROR - "A configuration is pending." after failed configuration

### ISSUE THREAD

**Issue by rschiefer** [opscode-cookbooks/dsc#18]
In testing cookbooks which utilize the DSC cookbook I am finding that when a DSC configuration fails it appears to leave the target node in a pending state.  Have others seen this issue?

       1) PowershellCmdletException -  dsc_resource[DownloadSmbShareResource] (AcmeWebServer2::default line 27) had an e
rror: PowershellCmdletException: PowershellCmdletException
         Powershell Cmdlet failed: A configuration is pending. Please run Update-DscConfiguration or
       Start-DscConfiguration command with -Force parameter.
           + CategoryInfo          : ResourceExists: (root/Microsoft/...gurationManag
          er:String) [], CimException
           + FullyQualifiedErrorId : MI RESULT 11
           + PSComputerName        : localhost

I propose this should be handled by the dsc cookbook. It should cleanup any pending DSC configuration work so the next attempt does not fail immediately

**Comment by GuillaumeCR** [comment]
I am seeing this issue. What was the resolution?
